### ISSUE TITLE
doesent work

### ISSUE THREAD

**Issue by 70V07** [AJGranowski/reddit-expanded-community-filter-userscript#140]
even I have muted the community can still see in **r/all**
I also have tried to put `// @match https://www.reddit.com/r/*` in the code
maybe I need to configure Reddit in some way?

**Comment by AJGranowski** [comment]
I'm unable to reproduce your issue, the script still works on my end.  
If you haven't already, try the [troubleshooting steps](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/wiki/Users#troubleshooting).

If that still doesn't work, could you provide some additional information?

**Desktop Environment:**
 - Browser [e.g. Chrome 1.2.3, Firefox 4.5.6]
 - Userscript Engine [e.g. Tampermonkey 1.2.3, Violentmonkey 4.5.6]

**Logs:**
1. Click **`Enable Debug Mode`** from the userscript menu and refresh the page.
2. Follow your reproduction steps.
3. Provide a copy of your console logs.
   * Chrome: Right-click one of the messages, then select Save as..., and save the console output to a text file.
   * Firefox: Right-click one of the messages, then select Save All Messages to File, and save the console output to a text file.

**Comment by 70V07** [comment]
I try to mute one popular subreddit, and check the userscript in `r/all`, muted counting is zero

- **Browser:** Edge 121.0.2277.112 (Official build pre-installed in Windows 11 Pro 64-bit)
- **Userscript Engine:** Violentmonkey 2.18.0 (Official build from MS addons store)
- **javacript version:** Reddit Expanded Community Filter 1.1.6 (not edited)

**there is 3 error I think related to the script in console:**

*number 1 appear just one time, number 2 and 3 appear many times*

1. [github.com-1707701670936.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14234724/github.com-1707701670936.log)

2. [github.com-1707701692583.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14234725/github.com-1707701692583.log)

3. [github.com-1707701709296.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14234726/github.com-1707701709296.log)

**Im using right now [Safing Pormaster](https://safing.io/) wich block some sites and IPs requests (maybe is this} but I tried to disable this app, and the result even is different, the filter still doesent work:**

*the third log is for sure related to the filter*

1. [+ www.reddit.com-1707702150304.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14234749/%2B.www.reddit.com-1707702150304.log)

2. [+ www.reddit.com-1707702185374.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14234750/%2B.www.reddit.com-1707702185374.log)

3. [3 www.reddit.com-1707702268589.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14234751/3.www.reddit.com-1707702268589.log)

**additional infos (just in case):**

*also I have tested some registry changes for mitigate issue security and for perfomance or personal testing, I know everything about changes maded by me in my system (but I dont think is the the problem, maybe Im wrong)*

*the only one can generate problems, maybe is DISABLE ANONYMOUS SID ENUMERATION if you use SID in the script*

- SAFELY SEARCH DLLs TO LOAD
_it may prevent operations like ReShade (shaders injector in games)_

- PREVENT WINDOWS FROM STORING LAN MANAGER HASH
_may affect compatibility with older systems that still require LM hashing_

- DISABLE ANONYMOUS SID ENUMERATION
_may cause compatibility issues with some applications or services that require access to anonymous SID information_

- HARDWARE ACCELERATED GPU SCHEDULING
_it could worsen performance and generate incompatibility problems_

**Comment by 70V07** [comment]
another maybe usefull info I forgot to add is I use Cloudflre DNS (with malware protection)

- `1.1.1.2`
- `1.0.0.2`

**Comment by AJGranowski** [comment]
The script is failing because it can't find the feed container.
```
Reddit expanded community filter.user.js:601  Error: Could not find main content element.
    at Reddit.getFeedContainer (Reddit expanded community filter.user.js:269:43)
    at Reddit expanded community filter.user.js:429:52
```

It looks like the script also needs to fall back to scraping for the access token.
```
Reddit expanded community filter.user.js:358  Error: Unable to retrieve ___r JSON from window.
    at AccessToken.fromWindow (Reddit expanded community filter.user.js:118:36)
    at Reddit expanded community filter.user.js:354:57
    at Reddit expanded community filter.user.js:325:20
    at new Promise (<anonymous>)
    at Reddit expanded community filter.user.js:324:5
    at RedditSession.updateAccessToken (Reddit expanded community filter.user.js:355:37)
    at RedditExpandedCommunityFilter.start (Reddit expanded community filter.user.js:443:26)
    at Reddit expanded community filter.user.js:596:4
    at Proxy.VM5mxxsj4upzd (Reddit expanded community filter.user.js:603:3)
    at Ut (injected-web.js:1:14789)
(anonymous) @ Reddit expanded community filter.user.js:358
Reddit expanded community filter.user.js:359  Failing back to scraping.
(anonymous) @ Reddit expanded community filter.user.js:359
```

This seems related to #78 and #79. Does the script work on [***new***.reddit.com/r/all](https://new.reddit.com/r/all/)?

**Comment by 70V07** [comment]
in [https://new.reddit.com/r/all/](https://new.reddit.com/r/all/) doesent work

**I maybe found the problem... this the results in console:**

- [ERROR new.reddit.com-1707783994570.log](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/files/14253972/ERROR.new.reddit.com-1707783994570.log)

> Reddit expanded community filter.user.js:601  Error: Could not find feed container: **Iteration limit exceeded.**

maybe is why I have many subreddits muted :|

**Comment by AJGranowski** [comment]
```
Error: Could not find feed container: Iteration limit exceeded.
```
That error occurs [here](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/blob/60b286b04d9799d2953f2eed45b517c588b54486/src/reddit/Reddit.ts#L42-L44) and means two things:
* The [main content element](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/blob/60b286b04d9799d2953f2eed45b517c588b54486/src/reddit/Reddit.ts#L21-L24) was found.
* There was a problem finding the feed container.

It seems like you were drafted into the redesign beta. The layout changes of the redesign break the script, and I haven't been able to access that layout since my account was discharged from the redesign. The script should still work on [new.reddit.com/r/all](https://new.reddit.com/r/all/) though.

Regarding the `Iteration limit exceeded` error: I get this error every now and then, and I think it's caused by the script executing before the page is completely loaded. Try refreshing the page if that error occurs.

----

Some action items:
* Add troubleshooting steps around the redesign beta.
* Make the script more tolerant in finding the feed container.
* Find a way to enroll in the redesign, and add support for that layout into the script.

**Comment by AJGranowski** [comment]
Reopen this issue if you're still experiencing problems with this script on [new.reddit.com](https://new.reddit.com/r/all) after a few refreshes.

**Comment by 70V07** [comment]
I have muted _r/worldnews_ for test, this is the result now...
I try to refresh few times as you suggest, and not a joke (really)
the post is surrounded with red dashes (https://**NEW**.reddit.com/r/all/):

![Screenshot 2024-02-13 065808](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/assets/46967291/7af8df10-402d-4aae-ad64-b49b915bccb4)

in https://**WWW**.reddit.com/r/all/ nothing change and the post still visible even related subreddit muted

anyway... I think for sure (at moment) the Reddit code is a mess of confusion, why I sometime change the CSS using Stylus and doesent work properly (too many changes), is the only site I know have 3 versions same time alive, this 3 versions _www old new_ are confused and intertwined. also, Ive disabled everything during the logs (before) like no extensions or other scripts, I hope it helped you and didnt waste your time, I will continue to follow the updates here on GitHub, if need something to test for this ask me here

**Comment by AJGranowski** [comment]
> the post is surrounded with red dashes (https://**NEW**.reddit.com/r/all/)

That's expected behavior in Debug Mode. [Disable debug mode by clicking **`Disable Debug Mode`** from the userscript menu](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/wiki/Users#posts-from-muted-communities-have-a-dashed-red-border-around-them) and those posts will get removed instead of being highlighted with a dashed red border.

> in https://**WWW**.reddit.com/r/all/ nothing change and the post still visible even related subreddit muted

I'm pretty sure this is because Reddit has drafted you into the redesign, and [this script doesn't currently support it](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/issues/143). I'll eventually add support, but for now you'll need to use [new.reddit.com](https://new.reddit.com/r/all) for this script to work.

> [this] is the only site I know have 3 versions same time alive, *www*, *old*, *new*

Apparently there's also [**sh**.reddit.com](https://sh.reddit.com/r/all/), which is what I think you're being served by default. This script doesn't currently support that layout.

> I hope it helped you and didnt waste your time, I will continue to follow the updates here on GitHub, if need something to test for this ask me here

Thank you for bringing this to my attention. I had [this exact same issue before](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/issues/78) myself, but I thought Reddit completely rolled it back. I guess they're still testing it with other people, so I'll add support for it in this script. Thank you for working with me to figure this out.

----

This script should still work for you on `new.reddit.com`. If you're still experiencing issues with this script on `new.reddit.com` after a few refreshes, feel free to reopen this issue. Remember to [disable debug mode](https://github.com/AJGranowski/reddit-expanded-community-filter-userscript/wiki/Users#posts-from-muted-communities-have-a-dashed-red-border-around-them) 😉.
